[project]
name = "igc-visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "rerun-sdk>=0.23.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
